### ISSUE TITLE
Is there some get_integer() as there is get_float() ?

### ISSUE THREAD

**Issue by kumy** [romain-dartigues/python-ihih#2]
I could find in the [doc](http://python-ihih.readthedocs.org/en/latest/api.html) the functions `get_float()`, `get_unicode()`, `get_str()`. but I'm unable to find some `get_integer()`.

Is this a bug in the doc, or the function is not implemented ?

**Comment by romain-dartigues** [comment]
Added in e997101.

**Comment by kumy** [comment]
Thx!
